name: simpa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.6.7
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^10.7.0
  firebase_app_check: ^0.2.2+7
  lottie: ^2.7.0
  dropdown_search: ^5.0.6
  curved_navigation_bar: ^1.0.6 #latest version
  intl: ^0.18.1  # Add this line

  # Other dependencies
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tayseer.png
    - assets/images/Simpa for app@4x.png
    - assets/images/User.png
    - assets/images/Cat.jpeg
    - assets/images/Dog.jpeg
    - assets/images/Bird.jpeg
    - assets/images/Rabbit.jpeg
    - assets/images/Other.jpeg
    - assets/animations/LoadingAnimation.json

  fonts:
    - family: Mikhak
      fonts:
        - asset: assets/fonts/mikhak/Mikhak-Bold.ttf
          weight: 700
        - asset: assets/fonts/mikhak/Mikhak-DS1-Regular.ttf
          weight: 200

    - family: MainFont
      fonts:
        - asset: assets/fonts/1/Fontspring-DEMO-grotesco-bold.otf