name: simpa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.6.7
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.7.0
  firebase_app_check: ^0.2.2+7
  intl: ^0.18.1  # Add this line

  # Other dependencies
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  package_info_plus: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tayseer.png
    - assets/images/Simpa for app@4x.png
    - assets/images/User.png
    - assets/images/animal.jpeg